@prefix deps:  <http://ontologi.es/doap-deps#> .

<http://purl.org/NET/cpan-uri/dist/String-Interpolate-Delayed/project>
	deps:runtime-requirement         [ deps:on "PadWalker 1.0"^^deps:CpanId ];
	deps:runtime-requirement         [ deps:on "PerlX::QuoteOperator 0.04"^^deps:CpanId ];
	deps:runtime-requirement         [ deps:on "String::Interpolate 0.3"^^deps:CpanId ];
	deps:runtime-requirement         [ deps:on "UNIVERSAL::ref 0.09"^^deps:CpanId ];
	deps:test-requirement            [ deps:on "Test::Fatal 0.007"^^deps:CpanId ].

